name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: 'sudo npm install -g newman'
      displayName: 'Install Newman'
      
    - script: 'ls -la $(System.DefaultWorkingDirectory)/automatedtesting/postman'
      displayName: 'List files in working directory'
    - script: 'sudo newman run $(System.DefaultWorkingDirectory)/automatedtesting/starterapis.json'
      displayName: 'Data validation Tests'
    # - script: 'sudo newman run $(System.DefaultWorkingDirectory)/automatedtesting/postman/DataValidationTestStarterAPIspostman_collection.json'
    #   displayName: 'Data validation Tests'

    # - script: 'sudo newman run $(System.DefaultWorkingDirectory)/automatedtesting/postman/RegressionTestStarterAPIspostman_collection.json'
    #   displayName: 'Regression Tests'
    
    