name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: 'sudo npm install -g newman'
      displayName: 'Install Newman'
      
    - script: 'ls -R $(System.DefaultWorkingDirectory)'
      displayName: 'List files in working directory'

    - script: 'sudo newman run $(System.DefaultWorkingDirectory)/starterapis.json'
      displayName: 'Run Regression Tests'
        
    
    